### ISSUE TITLE
/workspace/container/docker-shopware/public is not shared from OS X

### ISSUE THREAD

**Issue by itinance** [ffuenf/docker-shopware#4]
On OSX (EL Capitain) with Docker 1.13.0 and docker-compose 1.10.0  i'll get this error with "docker-compose up --build":

> ERROR: for data  Cannot start service data: Mounts denied: ces for more info.
> .
> /workspace/container/docker-shopware/public
> is not shared from OS X and is not known to Docker.
> 

Is there any chance to use this container on OSX/MacOS or at least to adjust this path in .env or somewhat else?

**Comment by arosenhagen** [comment]
We had huge performance issues with this docker-setup (due to NFS shares) - so we lately switched to a vagrant-based setup which is way faster. Please have a look at [shopware-vagrant](https://github.com/ffuenf/shopware-vagrant) as we might discontinue this project.

**Comment by itinance** [comment]
Thx for clarifying. We've ended up also with shopware-vagrant. 
However, you should mark this repo as "discontinued" :)
